---
- name: install pyenv
  hosts: all
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install pyenv dendencies
      apt:
        pkg:
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncurses5-dev
          - xz-utils
          - tk-dev
          - libffi-dev
          - liblzma-dev
          - python-openssl
          - git
        state: latest
      become: yes
    - name: Make checkout directory
      file:
        path: "{{ pyenv_tmp_dir }}"
        state: directory
    - name: Get pyenv source
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: "{{ pyenv_tmp_dir }}"
        mode: 0755
    - name: Run pyenv installer
      command: "{{ pyenv_tmp_dir|quote }}/pyenv-installer"
      args:
        creates: "{{ pyenv_root }}"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Clean up
      file:
        path: "{{ pyenv_tmp_dir }}"
        state: absent
    - name: set pyenv home.
      lineinfile:
        line: export PYENV_ROOT=$HOME/.pyenv
        path: /home/{{ user|mandatory }}/.bashrc
        state: present
    - name: Add pyenv to path for user.
      lineinfile:
        line: export PATH="$PYENV_ROOT/bin:$PATH"
        path: "/home/{{ user|mandatory }}/.bashrc"
        state: present
    - name: Install python 3.6
      command: "{{ pyenv_root }}/bin/pyenv install 3.6.11"
      args:
        creates: "{{ pyenv_root }}/versions/3.6.11"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Install python 3.7
      command: "{{ pyenv_root }}/bin/pyenv install 3.7.8"
      args:
        creates: "{{ pyenv_root }}/versions/3.7.8"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Install python 3.8
      command: "{{ pyenv_root }}/bin/pyenv install 3.8.5"
      args:
        creates: "{{ pyenv_root }}/versions/3.8.5"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Declare python 3.8 as global
      command: "{{ pyenv_root }}/bin/pyenv global 3.8.5"
      become_user: "{{ user|mandatory }}"
      become: yes
      
        